name: Build and Test Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 310
          channels: conda-forge

      - name: Create Conda environment
        run: conda create --name pyforestscan_env python=3.10 pdal -c conda-forge

      - name: Activate Conda environment and install dependencies
        shell: bash -l {0}
        run: |
          conda activate pyforestscan_env
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests
        shell: bash -l {0}
        run: |
          conda activate pyforestscan_env
          pytest