name: Build and Test Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.10
          channels: conda-forge

      - name: Create and install dependencies in Conda environment
        run: |
          conda create --name pyforestscan_env python=3.10 pdal -c conda-forge
          conda run -n pyforestscan_env pip install -r requirements.txt
          conda run -n pyforestscan_env pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          conda run -n pyforestscan_env pytest