name: JOSS PDF Generation

on:
  push:
    paths:
      - 'paper/**'
      - '.github/workflows/paper.yml'

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@v1
        with:
          journal: joss
          paper-path: paper/paper.md

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper.pdf
